<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SalonVerification\**" />
    <EmbeddedResource Remove="SalonVerification\**" />
    <None Remove="SalonVerification\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="A1\DTOs\" />
    <Folder Include="A1\Requests\" />
    <Folder Include="A1\Responses\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="9.5.4" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="9.5.4" />
  </ItemGroup>

</Project>
